### get all boards

GET http://localhost:3000/board

### get board by id (1)

GET http://localhost:3000/board/1

### create new board
POST http://localhost:3000/board
Content-Type: application/json

{
    "name": "Board 1"
}

### update board with id (1)
PUT http://localhost:3000/board/1
Content-Type: application/json

{
    "name": "Test"
}


### delete board with id (1)
DELETE http://localhost:3000/board/1

