### GET all boards

GET http://localhost:3000/board

### GET board by id

GET http://localhost:3000/board/1

### POST new board
POST http://localhost:3000/board
Content-Type: application/json

{
    "name": "Board 1"
}

### PUT board
PUT http://localhost:3000/board/1
Content-Type: application/json

{
    "name": "Test"
}


### DELETE board
DELETE http://localhost:3000/board/1

